version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - EXPO_DEVTOOLS_PORT=19002
      - EXPO_METRO_PORT=8081
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
      - EXPO_HOST=localhost 